<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
    <NoWarn>$(NoWarn);NU1507</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="CommunityToolkit.Maui" Version="9.1.1" />
    <PackageVersion Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Debug" Version="8.0.1" />
    <PackageVersion Include="Microsoft.Maui.Controls" Version="10.0.51" />
    <PackageVersion Include="Microsoft.Maui.Controls.Compatibility" Version="10.0.51" />
  </ItemGroup>
</Project>